export const SEQUELIZE_TOKEN = 'SEQUELIZE_TOKEN';
export const MIGRATOR_TOKEN = 'MIGRATOR_TOKEN';
export const MODEL_FACTORY_TOKEN = 'MODEL_FACTORY_TOKEN';
export const DATABASE_OPTIONS_TOKEN = 'DATABASE_OPTIONS';
